version: '3.8'
services:
  db:
    container_name: db_server
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    env_file:
      - .env
  pgadmin:
    container_name: pgadmin_server
    image: dpage/pgadmin4
    restart: always
    depends_on:
     - db
    ports:
      - "5050:80"
    env_file:
      - .env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  postgres_data:
  pgadmin-data:
