### Sign up
POST http://localhost:3001/auth/signup
Content-Type: application/json

{
    "email": "asd@asd.com",
    "username": "asd",
    "password": "asd"
}

### Login
# @name login
POST http://localhost:3001/auth/login
Content-Type: application/json

{
    "email": "asd@asd.com",
    "password": "asd"
}
### Variable access token
@accessToken = {{login.response.body.$.accessToken}}

### Replace this with a Pokemon ID
@pokemon = 41f8e6ea-3a39-4f89-8716-9dbc3d2d1ae6

### Get all
GET http://localhost:3001/pokemon
Authorization: Bearer {{accessToken}}

### Get a pokemon
GET http://localhost:3001/pokemon/{{pokemon}}
Authorization: Bearer {{accessToken}}

### Create
PUT http://localhost:3001/pokemon
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "name": "Pikachu",
    "type": "Electric",
    "hp": 60,
    "power": 20,
    "weaknessType": "Ground",
    "weaknessMultiplier": 2,
    "resistanceType": "Steel",
    "resistanceDecrement": 20
}

### Update
POST http://localhost:3001/pokemon
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "id": "{{pokemon}}",
    "weaknessMultiplier": 2
}

### Delete
DELETE http://localhost:3001/pokemon/{{pokemon}}
Authorization: Bearer {{accessToken}}


### Simulate a battle
GET http://localhost:3001/pokemon/simulation/{{pokemon}}/99a0efce-19e0-4baa-bbb0-dae778b37706
Authorization: Bearer {{accessToken}}

### Analyze Pokemon
GET http://localhost:3001/pokemon/analyze/{{pokemon}}
Authorization: Bearer {{accessToken}}


### Bulk Create
PUT http://localhost:3001/pokemon/bulk
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "pokemons": [
        {
            "name": "Pikachu",
            "type": "Electric",
            "hp": 60,
            "power": 20,
            "weaknessType": "Ground",
            "weaknessMultiplier": 2,
            "resistanceType": "Steel",
            "resistanceDecrement": 20
        },
        {
            "name": "Charizard",
            "type": "Fire",
            "hp": 180,
            "power": 120,
            "weaknessType": "Water",
            "weaknessMultiplier": 2,
            "rarity": "rare"
        },
        {
            "name": "Onix",
            "type": "Ground",
            "hp": 90,
            "power": 40,
            "weaknessType": "Plant",
            "weaknessMultiplier": 1.5
        },
        {
            "name": "Feraligatr",
            "type": "Water",
            "hp": 180,
            "power": 160,
            "weaknessType": "Electric",
            "weaknessMultiplier": 2,
            "rarity": "rare"
        },
        {
            "name": "Sneasel",
            "type": "Dark",
            "hp": 70,
            "power": 20,
            "weaknessType": "Plant",
            "weaknessMultiplier": 2
        },
        {
            "name": "Scizor",
            "type": "Steel",
            "hp": 120,
            "power": 60,
            "weaknessType": "Fire",
            "weaknessMultiplier": 2,
            "resistanceType": "Psychic",
            "resistanceDecrement": 20,
            "rarity": "rare"
        },
        {
            "name": "Treecko",
            "type": "Psychic",
            "hp": 40,
            "power": 10,
            "weaknessType": "Fire",
            "weaknessMultiplier": 1.5,
            "resistanceType": "Water",
            "resistanceDecrement": 30
        },
        {
            "name": "Mudkip",
            "type": "Water",
            "hp": 40,
            "power": 10,
            "weaknessType": "Electric",
            "weaknessMultiplier": 1.5,
            "resistanceType": "Fire",
            "resistanceDecrement": 30
        },
        {
            "name": "Torchic",
            "type": "Fire",
            "hp": 40,
            "power": 10,
            "weaknessType": "Water",
            "weaknessMultiplier": 1.5,
            "resistanceType": "Electric",
            "resistanceDecrement": 30
        },
        {
            "name": "Grovyle",
            "type": "Plant",
            "hp": 40,
            "power": 10,
            "weaknessType": "Fire",
            "weaknessMultiplier": 2,
            "resistanceType": "Water",
            "resistanceDecrement": 30
        },
        {
            "name": "Combusken",
            "type": "Fire",
            "hp": 40,
            "power": 10,
            "weaknessType": "Water",
            "weaknessMultiplier": 1.5,
            "resistanceType": "Electric",
            "resistanceDecrement": 30,
            "rarity": "uncommon"
        },
        {
            "name": "Marshtomp",
            "type": "Water",
            "hp": 40,
            "power": 10,
            "weaknessType": "Electric",
            "weaknessMultiplier": 1.5,
            "resistanceType": "Fire",
            "resistanceDecrement": 30
        },
        {
            "name": "Blaziken",
            "type": "Fire",
            "hp": 40,
            "power": 10,
            "weaknessType": "Water",
            "weaknessMultiplier": 1.5,
            "resistanceType": "Electric",
            "resistanceDecrement": 30,
            "rarity": "uncommon"
        },
        {
            "name": "Sceptile",
            "type": "Plant",
            "hp": 40,
            "power": 10,
            "weaknessType": "Fire",
            "weaknessMultiplier": 1.5,
            "resistanceType": "Water",
            "resistanceDecrement": 30
        }
    ]
}
