### Get a pokemon
GET http://localhost:3000/pokemon/3a1ff330-6a4b-4cf7-bc79-dd7fa36b181a

### Get all
GET http://localhost:3000/pokemon

### Create
PUT http://localhost:3000/pokemon
Content-Type: application/json

{
    "name": "Pikachu",
    "type": "Electric",
    "hp": 60,
    "power": 20
}

### Bulk Create
PUT http://localhost:3000/pokemon/bulk
Content-Type: application/json

{
    "pokemons": [
        {
            "name": "Pikachu",
            "type": "Electric",
            "hp": 60,
            "power": 20,
            "weaknessType": "Ground",
            "weaknessMultiplier": 1,
            "resistanceType": "Steel",
            "resistanceDecrement": 20
        },
        {
            "name": "Charizard",
            "type": "Fire",
            "hp": 180,
            "power": 120,
            "weaknessType": "Water",
            "weaknessMultiplier": 2
        },
        {
            "name": "Onix",
            "type": "Ground",
            "hp": 90,
            "power": 40,
            "weaknessType": "Plant",
            "weaknessMultiplier": 1
        },
        {
            "name": "Feraligatr",
            "type": "Electric",
            "hp": 180,
            "power": 160,
            "weaknessType": "Electric",
            "weaknessMultiplier": 2
        },
        {
            "name": "Sneasel",
            "type": "Electric",
            "hp": 70,
            "power": 20,
            "weaknessType": "Plant",
            "weaknessMultiplier": 2
        },
        {
            "name": "Scizor",
            "type": "Steel",
            "hp": 60,
            "power": 20,
            "weaknessType": "Fire",
            "weaknessMultiplier": 2,
            "resistanceType": "Psychic",
            "resistanceDecrement": 20
        },
        {
            "name": "Treecko",
            "type": "Psychic",
            "hp": 40,
            "power": 10,
            "weaknessType": "Fire",
            "weaknessMultiplier": 1,
            "resistanceType": "Water",
            "resistanceDecrement": 30
        }
    ]
}

### Update
POST http://localhost:3000/pokemon
Content-Type: application/json

{
    "id": "d05b6e6d-ed4f-4a1d-bf1d-ae6af93a01ed",
    "type": "Water"
}

### Delete
DELETE http://localhost:3000/pokemon/:id


### Simulate a battle
GET http://localhost:3000/pokemon/simulation/d05b6e6d-ed4f-4a1d-bf1d-ae6af93a01ed/12794566-890c-471b-a20a-a7ad8fa5c6fd

### Simulate a battle (Pikachu vs Onix)
GET http://localhost:3000/pokemon/simulation/5ccffec4-c36f-43cd-aa6e-cd407fb38cdd/e37b539b-16a8-49d1-9c09-f2ca96e9c2b9

### Analyze Pokemon
GET http://localhost:3000/pokemon/analyze/5ccffec4-c36f-43cd-aa6e-cd407fb38cdd